# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "78a135d7e13d44a5881948779120268c"
name = "regional-revenue-app"
application_url = "https://detection-donated-awards-senator.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "werd-test-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_payment_customizations,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://detection-donated-awards-senator.trycloudflare.com/auth/callback",
  "https://detection-donated-awards-senator.trycloudflare.com/auth/shopify/callback",
  "https://detection-donated-awards-senator.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
